services:
  react:
    image: node:20-alpine
    container_name: react
    working_dir: /app
    ports:
      - "${REACT_PORT}:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    command: >
      sh -lc 'cd /app &&
      if [ ! -f package.json ]; then
        echo ">> No hay package.json: creando Vite...";
        npx --yes create-vite@latest . -- --template react && npm install;
      else
        if [ ! -d node_modules ]; then npm install; fi;
      fi;
      npm run dev -- --host 0.0.0.0'
    networks: [chatnet]

networks:
  chatnet:
    external: true
