server {
  listen 80;
  server_name _;

  root /var/www/app/public;
  index index.php index.html;

  # Ruta principal + preflight
  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  # PHP-FPM
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass php:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
  }

  # Estáticos
  location ~* \.(jpg|jpeg|png|gif|css|js|ico|svg|woff2?)$ {
    try_files $uri =404;
    access_log off;
    expires 7d;
  }

  client_max_body_size 50m;
}
