version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: santi
      MYSQL_DATABASE: prueba
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psanti"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build: ./backend
    container_name: fastapi-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}  # Cambio de OpenAI a Gemini
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=santi
      - MYSQL_DATABASE=prueba
    ports:
      - "8000:8000"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
